export enum CONTRACT_NAMES {
    BOOL_COMPTROLLER = "BoolComptroller",
    FALSE_MARKER_METHOD_COMPTROLLER = "FalseMarkerMethodComptroller",
    COMPTROLLER_HARNESS = "ComptrollerHarness",
    SIMPLE_PRICE_ORACLE = "SimplePriceOracle",
    UNITROLLER = "Unitroller",
    INTEREST_RATE_MODEL_HARNESS = "InterestRateModelHarness",
    FALSE_MARKER_METHOD_INTEREST_RATE_MODEL = "FalseMarkerMethodInterestRateModel",
    JUMP_RATE_MODELV2 = "JumpRateModelV2",
    TRIPLE_SLOPE_RATE_MODEL = "TripleSlopeRateModel",
    BETHER_HARNESS = "BEtherHarness",
    ERC20_HARNESS = "ERC20Harness",
    CURVE_TOKEN_HARNESS = "CurveTokenHarness",
    YVAULT_V1_TOKEN_HARNESS = "YVaultV1TokenHarness",
    YVAULT_V2_TOKEN_HARNESS = "YVaultV2TokenHarness",
    EVIL_TRANSFER_TOKEN = "EvilTransferToken",
    FAUCET_NON_STANDARD_TOKEN = "FaucetNonStandardToken",
    LP_TOKEN_HARNESS = "LPTokenHarness",
    WETH9 = "WETH9",
    BCAPABLE_ERC20_DELEGATE = "BCapableErc20Delegate",
    BERC20_DELEGATOR = "BErc20Delegator",
  }