const CONTRACT_NAMES = {
  COMPTROLLER: "Comptroller",
  COMPTROLLER_G1: "ComptrollerG1",
  COMPTROLLER_HARNESS: "ComptrollerHarness",
  BOOL_COMPTROLLER: "BoolComptroller",
  ECHO_TYPES_COMPTROLLER: "EchoTypesComptroller",
  COMP_SCENARIO: "CompScenario",
  COMP: "Comp",
  FALSE_MARKER_METHOD_COMPTROLLER: "FalseMarkerMethodComptroller",
  SIMPLE_PRICE_ORACLE: "SimplePriceOracle",
  UNITROLLER: "Unitroller",
  INTEREST_RATE_MODEL_HARNESS: "InterestRateModelHarness",
  FALSE_MARKER_METHOD_INTEREST_RATE_MODEL: "FalseMarkerMethodInterestRateModel",
  JUMP_RATE_MODELV2: "JumpRateModelV2",
  TRIPLE_SLOPE_RATE_MODEL: "TripleSlopeRateModel",
  BETHER_HARNESS: "BEtherHarness",
  ERC20_HARNESS: "ERC20Harness",
  CURVE_TOKEN_HARNESS: "CurveTokenHarness",
  YVAULT_V1_TOKEN_HARNESS: "YVaultV1TokenHarness",
  YVAULT_V2_TOKEN_HARNESS: "YVaultV2TokenHarness",
  EVIL_TRANSFER_TOKEN: "EvilTransferToken",
  FAUCET_NON_STANDARD_TOKEN: "FaucetNonStandardToken",
  LP_TOKEN_HARNESS: "LPTokenHarness",
  WETH9: "WETH9",
  BCAPABLE_ERC20_DELEGATE: "BCapableErc20Delegate",
  BERC20_DELEGATOR: "BErc20Delegator",
  BERC20_DELEGATE_HARNESS: "BErc20DelegateHarness",
  BCOLLATERAL_CAP_ERC20_DELEGATE_HARNESS: "BCollateralCapErc20DelegateHarness",
  BCOLLATERAL_CAP_ERC20_DELEGATOR: "BCollateralCapErc20Delegator",
  BCOLLATERAL_CAP_ERC20_DELEGATE: "BCollateralCapErc20Delegate",
  BCOLLATERAL_CAP_ERC20_NO_INTEREST_DELEGATE_HARNESS:
    "BCollateralCapErc20NoInterestDelegateHarness",
  BWRAPPED_NATIVE_DELEGATE_HARNESS: "BWrappedNativeDelegateHarness",
  BWRAPPED_NATIVE_DELEGATOR: "BWrappedNativeDelegator",
  BCOLLATERAL_CAP_ERC20_CHECK_REPAY_DELEGATE_HARNESS:
    "BCollateralCapErc20CheckRepayDelegateHarness",
  MOCK_REFERENCE: "MockReference",
  MOCK_BTOKEN_ADMIN: "MockBTokenAdmin",
  CURVE_SWAP_HARNESS: "CurveSwapHarness",
  MOCK_LIQUIDITY_MINING: "MockLiquidityMining",
  EVIL_ACCOUNT: "EvilAccount",
  EVIL_ACCOUNT2: "EvilAccount2",
  FLASHLOAN_RECEIVER: "FlashloanReceiver",
  FLASHLOAN_AND_MINT: "FlashloanAndMint",
  FLASHLOAN_AND_REPAY_BORROW: "FlashloanAndRepayBorrow",
  FLASHLOAN_TWICE: "FlashloanTwice",
  FLASHLOAN_RECEIVER_NATIVE: "FlashloanReceiverNative",
  FLASHLOAN_AND_MINT_NATIVE: "FlashloanAndMintNative",
  FLASHLOAN_AND_REPAY_BORROW_NATIVE: "FlashloanAndRepayBorrowNative",
  FLASHLOAN_TWICE_NATIVE: "FlashloanTwiceNative",
};

module.exports = { CONTRACT_NAMES };
